apiVersion: v1
kind: Service
metadata:
  name: cloudnativebasicspring-service
  namespace: k8-booster
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudnativebasicspring
  type: LoadBalancer
